vich_uploader:
    db_driver: orm

    metadata:
        type: attribute
        
    mappings:
        picture_file:
            uri_prefix: /uploads/images/pictures
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
